# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: dolphinnext-m-constructqc-1.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - fastqc=0.11.8
  - star=2.6.1d # don't upgrade me - 2.7X indices incompatible with iGenomes.
  - samtools=1.3
  - trimmomatic=0.39
  - boto3=1.18.21
  - igvtools=2.5.3
  - bedtools
  - ucsc-wigToBigWig=377
  - ucsc-bedgraphtobigwig
  - r-ggplot2
  - r-ggbeeswarm
  - r-pheatmap
  - r-ggrepel
  - ghostscript
  - bamutil=1.0.15
  - pysamstats=1.1.2
  - biopython
  - r-optparse
  - r-testit
  - r-formattable
  - r-plotrix
  - r-readxl
  - r-tidyverse
  - r-cowplot
  - numpy
  - seaborn
  - matplotlib
